# Generated by Django 5.1.5 on 2025-08-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('encoding', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataNettoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name_nettoyee', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('table_originale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_nettoyees', to='Back_Front.dataoriginal')),
            ],
        ),
        migrations.CreateModel(
            name='DataTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name_transformee', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('target_column', models.CharField(blank=True, max_length=255, null=True)),
                ('table_nettoyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_transformees', to='Back_Front.datanettoyer')),
            ],
        ),
    ]
